apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "ArgoCD Deploy"
inputs:
  url:
    description: 'argocd url'
    required: true
  token:
    description: 'argocd token'
    required: true
  namespace:
    description: 'namespace'
    required: true
  workflow-name:
    description: 'workflow name'
    required: true
  parameters: 
    description: 'parameters as json'
    default: '{}'

runs:
  using: composite
  steps:
    - id: invoke-argocd-action
      name: invoke-argocd-action
      uses: docker://public.ecr.aws/l7o7z1g8/actions/argocd-actions:main-3cb45ae6495fae5ef6b4470476967f4353012b05
      shell: sh
      env: 
        CONFIG_JSON: '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"ARGOCDACTIONS","password":"${{ inputs.token }}","namespace":"${{ inputs.namespace }}","jobName":"${{ inputs.workflow-name }}","parameters":${{inputs.parameters}}}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./argo_actions_app invoke -d $CONFIG_JSON
